### ISSUE TITLE
Нужны подробности по ДЗ

### ISSUE THREAD

**Issue by AleksandrNagovitsyn** [AleksandrNagovitsyn/Megafon#1]
@coursar Я правильно понял, надо создать класс родитель "Тариф" и к нему создать несколько дочерних, в которых будут инициализироваться нужные данные, и добавляться новые при необходимости? 
https://github.com/AleksandrNagovitsyn/Megafon/blob/76c6df4a28a0d97baea21bd9b9d175709fd4f060/src/main/java/ru/itpark/TurnOnLook.java#L4-L10

По большому счету, общего среди них всех только название, цена и ссылка "Подробнее":

https://github.com/AleksandrNagovitsyn/Megafon/blob/76c6df4a28a0d97baea21bd9b9d175709fd4f060/src/main/java/ru/itpark/Tariff.java#L4-L6

То есть надо  создать класс родитель Тариф, потом еще около 15 дочерних классов, для каждого прописать недостающие свойства и инициализировать?

**Comment by coursar** [comment]
Классов должно быть всего 4.

Родитель для всех - Тариф, и дальше 3 раздела: Включайся, для планештов и остальные.

**Comment by coursar** [comment]
У каждого тарифа ещё есть id
